version: "3.1"

services:
  php:
    build: .
    ports:
      - "8080:80"
    depends_on:
      - mysql
    networks:
      - my-network

  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./mysql-init:/docker-entrypoint-initdb.d
    networks:
      - my-network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "8081:80"
    networks:
      - my-network

networks:
  my-network:
    driver: bridge
